'use client';

import {useEffect, useState} from 'react';
import {surveillanceApi, type CopilotResult, type KafkaStatus, type LiveCase, type ManagementMetrics} from './api';

type View = 'presentation' | 'input' | 'cases' | 'lab' | 'clusters' | 'entities' | 'management' | 'controls';
type CaseTab = 'assessment' | 'copilot' | 'evidence' | 'workflow' | 'governance';
type SurveillanceCase = LiveCase;

const cases: SurveillanceCase[] = [
  {id:'WT-102',instrument:'NOVA.L',typology:'Wash trading',risk:94,confidence:96,alerts:17,accounts:'A-104 ↔ A-882',driver:'Linked-account round trips',color:'#d64545',owner:'M. Rao',status:'In review',age:'2h 14m',entityLift:23},
  {id:'SP-204',instrument:'ALTO.N',typology:'Spoofing',risk:91,confidence:93,alerts:23,accounts:'TRD-441',driver:'Layered orders cancelled near execution',color:'#e86f3e',owner:'J. Chen',status:'Unassigned',age:'3h 48m',entityLift:0},
  {id:'FR-118',instrument:'QUAD.N',typology:'Front-running',risk:87,confidence:90,alerts:11,accounts:'EMP-17 ↔ CLIENT-04',driver:'Trading before large client orders',color:'#ee9143',owner:'A. Patel',status:'Supervisor review',age:'6h 05m',entityLift:14},
  {id:'WT-071',instrument:'MEGA.O',typology:'Wash trading',risk:48,confidence:95,alerts:19,accounts:'A-251',driver:'Market context reduces concern',color:'#d0a52a',owner:'S. Lewis',status:'In review',age:'1d 2h',entityLift:0},
  {id:'WT-088',instrument:'LIQD.P',typology:'Wash trading',risk:22,confidence:90,alerts:8,accounts:'A-390',driver:'Behaviour within baseline',color:'#2d9b75',owner:'K. Singh',status:'Pending closure',age:'1d 7h',entityLift:0},
];

const caseDetails: Record<string, {journey:{label:string;score:number}[]; inc:string[]; dec:string[]; narrative:string; citations:string[]}> = {
  'WT-102':{journey:[{label:'Rule',score:51},{label:'Behaviour',score:67},{label:'Market',score:71},{label:'Exposure',score:83},{label:'Entity links',score:94}],inc:['7 opposing cycles · +16','8s median time delta · +15','99.8% quantity match · +13','Common beneficial owner · +18','0.3% net exposure · +17'],dec:['Moderate volatility · −3','Single price gap · −1'],narrative:'Seven repeated opposing cycles between accounts with a verified ownership link created high turnover while returning close to the opening position. The evidence supports escalation for human investigation, not a finding of abuse.',citations:['Trade:T183','Trade:T187','Position:P905','Ownership:O29']},
  'SP-204':{journey:[{label:'Rule',score:58},{label:'Cancellations',score:76},{label:'Price impact',score:84},{label:'Peer baseline',score:91},{label:'Entity links',score:91}],inc:['94% cancellation ratio · +15','Orders placed across 4 levels · +13','Price moved 18 bps · +12','6 repeated episodes · +16'],dec:['Liquid opening session · −4'],narrative:'Repeated multi-level orders were cancelled as opposite-side executions occurred. The pattern is unusual for the trader cohort and warrants review of intent and surrounding communications.',citations:['Order:O441','Order:O447','Market:M204','Trade:T390']},
  'FR-118':{journey:[{label:'Rule',score:49},{label:'Timing',score:68},{label:'Price impact',score:76},{label:'Client link',score:87},{label:'Entity links',score:87}],inc:['Trade preceded client order by 42s · +15','Common desk relationship · +14','Favourable 11 bps movement · +12','5 repeated episodes · +10'],dec:['Partial existing position · −5'],narrative:'Employee-account trading repeatedly preceded large client orders in the same instrument. Desk relationships and timing elevate priority; a reviewer must assess information access and intent.',citations:['Trade:T511','ClientOrder:CO44','Access:A17','Market:M118']},
  'WT-071':{journey:[{label:'Rule',score:61},{label:'Behaviour',score:68},{label:'Market',score:48},{label:'Exposure',score:50},{label:'Entity links',score:48}],inc:['Close opposing trades · +12','Four recurrence cycles · +8'],dec:['Top-decile liquidity · −10','Event volatility · −8','Meaningful end position · −7'],narrative:'High market volatility, genuine position change and a normal strategy baseline reduce priority. A reviewer should verify the event context before disposition.',citations:['Trade:T271','Position:P711','Market:M071']},
  'WT-088':{journey:[{label:'Rule',score:55},{label:'Behaviour',score:59},{label:'Market',score:35},{label:'Exposure',score:26},{label:'Entity links',score:22}],inc:['Two close reversals · +7'],dec:['54th peer percentile · −10','Meaningful holding duration · −8','Large exposure change · −9'],narrative:'Trading resembles the participant baseline and produced genuine economic exposure. Closure remains subject to documented human review and supervisor approval.',citations:['Trade:T881','Profile:B390','Position:P888']},
};

const scenarioPresets = {
  wash:{name:'Linked-account wash trading',typology:'Wash trading',description:'Opposing trades return linked accounts close to their starting positions.',pattern:92,entity:100,context:18,evidence:100},
  spoof:{name:'Layering / spoofing',typology:'Spoofing',description:'Large layered orders are cancelled as opposite-side executions occur.',pattern:95,entity:10,context:30,evidence:92},
  front:{name:'Potential front-running',typology:'Front-running',description:'Employee trading repeatedly precedes large client orders.',pattern:86,entity:75,context:25,evidence:95},
  benign:{name:'Volatility-driven reversal',typology:'Contextual control',description:'A rule alert is explained by volatility and genuine exposure.',pattern:56,entity:0,context:92,evidence:88},
};

function riskBand(risk:number){return risk>=80?'HIGH':risk>=45?'MEDIUM':'LOW'}
function apiTypology(value:string){return value.toUpperCase().replaceAll('-','_').replaceAll(' ','_')}

function CasesView({caseSource,live}:{caseSource:SurveillanceCase[];live:boolean}){
  const [selected,setSelected]=useState(caseSource[0]?.id||'WT-102');
  const [tab,setTab]=useState<CaseTab>('assessment');
  const [decision,setDecision]=useState('');
  const [reason,setReason]=useState('');
  const [confirmed,setConfirmed]=useState(false);
  const [audit,setAudit]=useState<string[]>(['10:38 · Case assigned to M. Rao','10:36 · AI assessment generated from 4 cited sources','10:35 · 17 alerts clustered into WT-102']);
  const [copilot,setCopilot]=useState<CopilotResult>();
  const [copilotBusy,setCopilotBusy]=useState(false);
  const [copilotError,setCopilotError]=useState('');
  useEffect(()=>{if(!caseSource.some(item=>item.id===selected)&&caseSource[0])setSelected(caseSource[0].id)},[caseSource,selected]);
  const c=caseSource.find(x=>x.id===selected)||caseSource[0]||cases[0];
  const detail=caseDetails[selected]||{journey:[{label:'Hybrid model',score:c.risk}],inc:[c.driver],dec:['Human review remains mandatory'],narrative:`${c.driver}. This live assessment prioritises the activity for human investigation and is not a finding of misconduct.`,citations:[`Trade:${c.accounts}`]};
  const canSubmit=Boolean(decision && reason.trim().length>=20 && confirmed);
  function chooseCase(id:string){setSelected(id);setTab('assessment');setDecision('');setReason('');setConfirmed(false);setCopilot(undefined);setCopilotError('')}
  async function runCopilot(){setCopilotBusy(true);setCopilotError('');try{const result=await surveillanceApi.copilot(c.id,{
      caseId:c.id,alertId:`ALT-${c.id}`,region:c.region||'EMEA',assetClass:c.assetClass||'FIXED_INCOME',
      typology:apiTypology(c.typology),priority:c.risk,evidenceCoverage:detail.citations.length?1:0,
      modelDisagreement:c.risk>=80?.42:.18,riskDrivers:detail.inc,riskReducers:detail.dec,
      timeline:detail.citations.slice(0,3).map((ref,index)=>`Event ${index+1} verified by ${ref}`),
      entityRelationships:c.entityLift>0?[`Verified relationship increased priority by ${c.entityLift} points`]:[],
      evidenceRefs:detail.citations,dataGaps:[]});setCopilot(result)}catch(error){setCopilotError(error instanceof Error?error.message:'Copilot unavailable')}finally{setCopilotBusy(false)}}
  async function submit(){if(!canSubmit)return;try{if(live)await surveillanceApi.decide(c.id,decision,reason);setAudit(old=>[`${new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})} · ${decision} recorded by authenticated reviewer — ${reason}`, ...old]);setDecision('');setReason('');setConfirmed(false);setTab('workflow')}catch(error){setAudit(old=>[`Decision failed: ${error instanceof Error?error.message:'API unavailable'}`,...old])}}
  return <div className="content robustContent">
    <section className="queue"><div className="sectionHead"><div><span className="eyebrow">RISK-BASED WORK QUEUE</span><h2>Cases requiring attention</h2></div><span className="live">● {live?'LIVE POSTGRESQL':'CONTROLLED DEMO'}</span></div>
      <div className="queueFilters"><button className="filterActive">Priority</button><button>Ageing</button><button>Unassigned 1</button></div>
      {caseSource.map(x=><button key={x.id} className={`caseRow robustRow ${selected===x.id?'selected':''}`} onClick={()=>chooseCase(x.id)}><span className="riskDot" style={{background:x.color}}>{x.risk}</span><span className="caseMain"><b>{x.id} <em className="typeTag">{x.typology}</em></b><em>{x.instrument} · {x.alerts} alerts · {x.age}</em></span><span className="caseDriver">{x.driver}<small>{x.owner} · {x.status}</small></span><span>›</span></button>)}
      <div className="compression"><div><span>ALERT-TO-CASE COMPRESSION</span><b>67%</b></div><div className="bar"><i/></div><p>1,247 rule alerts organised into 412 investigation cases</p></div>
    </section>
    <section className="casePanel"><div className="caseTitle"><div><span className="eyebrow">{c.typology.toUpperCase()} · CASE {c.id}</span><h2>{c.driver}</h2><p>{c.accounts} · owner {c.owner} · aged {c.age}</p></div><div className="score"><b>{c.risk}</b><span>/100</span><em>{riskBand(c.risk)} PRIORITY</em><small>{c.confidence}% confidence</small></div></div>
      <div className="controlBanner"><b>AI role:</b> prioritise and explain <i/> <b>Human role:</b> investigate and decide</div>
      <div className="tabs">{(['assessment','copilot','evidence','workflow','governance'] as CaseTab[]).map(t=><button key={t} onClick={()=>setTab(t)} className={tab===t?'active':''}>{t[0].toUpperCase()+t.slice(1)}</button>)}</div>
      {tab==='assessment'&&<><div className="journey"><span className="eyebrow">EXPLAINABLE RISK JOURNEY</span><div className="journeyTrack">{detail.journey.map((j,i)=><div key={j.label} className="journeyStep"><b>{j.score}</b><span>{j.label}</span>{i<4&&<i>→</i>}</div>)}</div></div><div className="narrative"><div><span className="eyebrow">EVIDENCE-GROUNDED SUMMARY</span><span className="grounded">100% CITED</span></div><p>{detail.narrative} {detail.citations.slice(0,3).map(x=><a key={x}>[{x}] </a>)}</p></div><div className="signals"><div><h3>↑ Risk-increasing evidence</h3>{detail.inc.map(x=><p key={x}>{x}</p>)}</div><div><h3>↓ Risk-reducing context</h3>{detail.dec.map(x=><p key={x}>{x}</p>)}</div></div></>}
      {tab==='copilot'&&<div className="copilotTab"><div className="copilotIntro"><div><span className="eyebrow">TOKEN-EFFICIENT INVESTIGATION COPILOT</span><h3>One guarded LLM call produces five investigator aids</h3><p>Local ML performs detection first. Only a compact, tokenised evidence packet reaches the LLM after eligibility, DLP and prompt-injection checks.</p></div><div className="tokenBadge"><b>≤450</b><span>output-token ceiling</span></div></div>{!copilot&&<div className="copilotReady"><div className="copilotFlow"><span>Local ML</span><i>→</i><span>Eligibility gate</span><i>→</i><span>DLP guardrail</span><i>→</i><span>Micro-RAG</span><i>→</i><span>Structured LLM</span><i>→</i><span>Citation check</span></div><button className="primary" disabled={copilotBusy} onClick={runCopilot}>{copilotBusy?'Running guarded analysis…':'Generate guarded copilot analysis'}</button>{copilotError&&<p className="copilotError">{copilotError}</p>}</div>}{copilot?.status==='GATED'&&<div className="safeAnswer"><b>No LLM call made:</b> {copilot.reason}. Tokens used: 0.</div>}{copilot?.status==='ABSTAINED'&&<div className="safeAnswer"><b>LLM output withheld:</b> {copilot.reason}. Continue with the verified local evidence; human review remains available.</div>}{copilot?.analysis&&<><div className="copilotResultHead"><span className="grounded">{copilot.grounded?'GUARDRAILS PASSED':'ABSTAINED'}</span><span>{copilot.status} · {copilot.playbookRefs.join(', ')}</span></div><div className="copilotGrid"><article><span>CASE SUMMARY</span><p>{copilot.analysis.summary}</p></article><article><span>COUNTER-HYPOTHESIS</span><p>{copilot.analysis.counterHypothesis}</p></article><article><span>NEXT BEST ACTIONS</span>{copilot.analysis.nextBestActions.map(item=><p key={item}>→ {item}</p>)}</article><article><span>EVIDENCE GAPS</span>{(copilot.analysis.missingEvidence.length?copilot.analysis.missingEvidence:['No material gap identified']).map(item=><p key={item}>• {item}</p>)}</article></div><div className="tokenLedger"><span><b>{String(copilot.tokenControl.actualInputTokens||copilot.tokenControl.estimatedInputTokens||'—')}</b> input tokens</span><span><b>{String(copilot.tokenControl.actualOutputTokens||'—')}</b> output tokens</span><span><b>{copilot.tokenControl.cacheHit?'Yes':'No'}</b> cache hit</span><span><b>{copilot.analysis.citedEvidenceRefs.length}</b> verified citations</span></div><p className="confidenceNote">{copilot.analysis.confidenceNote} Human review remains mandatory.</p></>}</div>}
      {tab==='evidence'&&<div className="evidenceTab"><div className="evidenceSummary"><span><b>{detail.citations.length}</b> verified sources</span><span><b>100%</b> claim coverage</span><span><b>0</b> unsupported claims</span></div><h3>Claim → metric → source record</h3><div className="lineage"><span>Linked activity</span><i>→</i><span>Ownership path = 97%</span><i>→</i><span>{detail.citations.map(x=><a key={x}>[{x}] </a>)}</span></div><div className="timeline"><p><b>10:14:22</b> Activity begins <a>[{detail.citations[0]}]</a></p><p><b>10:14:30</b> Opposing activity detected <a>[{detail.citations[1]||detail.citations[0]}]</a></p><p><b>10:15:06</b> Context snapshot frozen <a>[{detail.citations.at(-1)}]</a></p></div><div className="safeAnswer"><b>Grounding control:</b> If evidence is unavailable, the copilot responds “Not supported by the case evidence” instead of creating an answer.</div></div>}
      {tab==='workflow'&&<div className="workflowTab"><div className="workflowStages"><b className="done">1 Assigned</b><i>→</i><b className="current">2 Investigating</b><i>→</i><b>3 Supervisor review</b><i>→</i><b>4 Finalised</b></div><h3>Immutable activity history</h3>{audit.map((event,i)=><p className="auditEvent" key={`${event}-${i}`}><span>{i===0?'●':'○'}</span>{event}</p>)}<div className="roleRule">Case closure and false-positive confirmation require supervisor approval.</div></div>}
      {tab==='governance'&&<div className="governance"><h3>Reproducibility and control record</h3><dl><dt>Risk model</dt><dd>Hybrid transparent surveillance v1.0</dd><dt>Calibration</dt><dd>Isotonic · validation set 2026.08</dd><dt>Feature snapshot</dt><dd>2026-08-25T10:35:00Z · immutable</dd><dt>Entity resolver</dt><dd>Exact + probabilistic linkage v1.0</dd><dt>Decision policy</dt><dd>Human review required</dd><dt>Data residency</dt><dd>Private deployment boundary</dd></dl><div className="warning">The copilot may summarise verified evidence. It cannot determine misconduct, contact a regulator, or close a case.</div></div>}
      <div className="review"><div className="reviewHead"><span className="eyebrow">CONTROLLED HUMAN DECISION</span><span>Signed in: M. Rao · Investigator</span></div><div className="decisionButtons">{['Escalate','Further review','False positive','Close'].map(d=><button key={d} className={decision===d?'chosen':''} onClick={()=>setDecision(d)}>{d}</button>)}</div>{decision&&<div className="decisionForm"><textarea aria-label="Decision rationale" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Required: explain the evidence and judgement supporting this action (minimum 20 characters)"/><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> I reviewed the cited evidence and accept accountability for this action.</label><button className="primary" disabled={!canSubmit} onClick={submit}>Record human decision</button>{decision==='Close'&&<small>Supervisor approval will be required before closure.</small>}</div>}</div>
    </section>
  </div>
}

function ScenarioLab(){
  const [preset,setPreset]=useState<keyof typeof scenarioPresets>('wash'); const [pattern,setPattern]=useState(92); const [entity,setEntity]=useState(100); const [context,setContext]=useState(18); const [evidence,setEvidence]=useState(100); const [run,setRun]=useState(1);
  const scenario=scenarioPresets[preset];
  function load(key:keyof typeof scenarioPresets){const s=scenarioPresets[key];setPreset(key);setPattern(s.pattern);setEntity(s.entity);setContext(s.context);setEvidence(s.evidence);setRun(0)}
  const risk=Math.max(3,Math.min(99,Math.round(18+pattern*.46+entity*.22-context*.28)));
  const confidence=Math.round(35+evidence*.45+Math.min(20,(pattern+entity+context)/15));
  return <div className="modulePage labLayout"><section className="modulePanel labControls"><div className="sectionHead"><div><span className="eyebrow">LIVE SCENARIO LAB</span><h2>Change the facts. Re-run the assessment.</h2></div><span className="live">NOT PRE-SCRIPTED</span></div><p className="intro">Choose a surveillance pattern, adjust the evidence, and see the prioritisation change. AI supports triage; it never determines misconduct.</p><div className="presetGrid">{Object.entries(scenarioPresets).map(([key,value])=><button key={key} onClick={()=>load(key as keyof typeof scenarioPresets)} className={preset===key?'selectedPreset':''}><b>{value.name}</b><small>{value.description}</small></button>)}</div><div className="sliders"><label><span>Pattern strength <b>{pattern}%</b></span><input type="range" min="0" max="100" value={pattern} onChange={e=>setPattern(+e.target.value)}/></label><label><span>Entity / information link <b>{entity}%</b></span><input type="range" min="0" max="100" value={entity} onChange={e=>setEntity(+e.target.value)}/></label><label><span>Legitimate market context <b>{context}%</b></span><input type="range" min="0" max="100" value={context} onChange={e=>setContext(+e.target.value)}/></label><label><span>Evidence completeness <b>{evidence}%</b></span><input type="range" min="0" max="100" value={evidence} onChange={e=>setEvidence(+e.target.value)}/></label></div><button className="runButton" onClick={()=>setRun(x=>x+1)}>▶ Run surveillance assessment</button></section>
    <section className="modulePanel labResult"><div className="resultTop"><div><span className="eyebrow">RESULT · RUN {run||'—'}</span><h2>{scenario.typology}</h2><p>{scenario.description}</p></div><div className={`labScore ${riskBand(risk).toLowerCase()}`}><b>{run?risk:'—'}</b><span>{run?riskBand(risk):'READY'}</span></div></div>{run>0&&<><div className="resultPipeline"><span><b>Rules</b>Known pattern</span><i>+</i><span><b>ML</b>Peer anomaly</span><i>+</i><span><b>Graph</b>Hidden links</span><i>−</i><span><b>Context</b>Risk reducers</span></div><div className="resultFacts"><article><span>MODEL CONFIDENCE</span><b>{Math.min(99,confidence)}%</b><small>{confidence<70?'Needs more data':'Sufficient for prioritisation'}</small></article><article><span>EVIDENCE COVERAGE</span><b>{evidence}%</b><small>{evidence<75?'Grounded summary withheld':'Summary may be generated'}</small></article><article><span>DECISION POLICY</span><b>Human</b><small>Mandatory investigation</small></article></div><div className="labExplanation"><span className="eyebrow">WHY THIS SCORE CHANGED</span><p><b>+{Math.round(pattern*.46)}</b> pattern strength · <b>+{Math.round(entity*.22)}</b> entity/information link · <b>−{Math.round(context*.28)}</b> legitimate market context</p></div>{evidence<75&&<div className="warning">AI abstention: evidence coverage is below 75%. The system will show the data gap and will not generate a factual case summary.</div>}<div className="nextStep"><b>Recommended workflow:</b> {risk>=80?'Assign to a senior investigator and preserve communications evidence.':risk>=45?'Review contextual evidence before deciding priority.':'Continue monitoring; human approval is still required before closure.'}</div></>}</section>
  </div>
}

function ClustersView(){return <div className="modulePage"><div className="metricStrip"><article><span>RAW ALERTS</span><b>1,247</b></article><i>→</i><article><span>CLUSTERED CASES</span><b>412</b></article><i>→</i><article><span>COMPRESSION</span><b>67%</b></article><i>·</i><article><span>VALIDATED PURITY</span><b>91%</b></article></div><section className="modulePanel"><div className="sectionHead"><div><span className="eyebrow">EXPLAINABLE ALERT CLUSTERS</span><h2>Every grouping has a business reason</h2></div><span className="live">NO BLACK-BOX MERGES</span></div><div className="clusterTable robustTable"><b>Case</b><b>Coverage</b><b>Why grouped</b><b>Risk</b>{cases.map(c=><div className="tableRow" key={c.id}><span>{c.id}<small>{c.alerts} alerts · {c.instrument}</small></span><span>{c.accounts}</span><span>{c.driver}; shared time, instrument, entity and exposure window</span><strong style={{color:c.color}}>{c.risk}</strong></div>)}</div></section><section className="clusterWhy"><div><span className="eyebrow">CASE WT-102</span><h3>17 alerts became one investigation</h3><p>67 trades · 4 accounts · 2 clients · 1 common owner · 7 round trips</p></div><div className="clusterFlow"><span>Time proximity</span><i>+</i><span>Instrument</span><i>+</i><span>Entity path</span><i>+</i><span>Exposure</span><i>→</i><b>WT-102</b></div></section><div className="qualityNote"><b>Quality control:</b> clusters with weak linkage remain separate. Investigators can split or merge cases, and every override becomes model-monitoring feedback.</div></div>}

function EntitiesView(){const[node,setNode]=useState('UBO-72');return <div className="modulePage entityLayout"><section className="modulePanel"><div className="sectionHead"><div><span className="eyebrow">ENTITY INTELLIGENCE</span><h2>A hidden relationship changes priority</h2></div><span className="live">LINK CONFIDENCE 97%</span></div><div className="entityImpact"><article><span>BEFORE ENTITY LINK</span><b>71</b><small>Rule + behaviour + market</small></article><i>+23</i><article><span>AFTER VERIFIED LINK</span><b>94</b><small>High-priority investigation</small></article></div><div className="entityGraph"><button onClick={()=>setNode('UBO-72')} className="node ubo">UBO-72<small>Beneficial owner</small></button><span className="edge e1"/><span className="edge e2"/><button onClick={()=>setNode('Client X')} className="node client n1">Client X<small>ABC Ltd</small></button><button onClick={()=>setNode('Client Y')} className="node client n2">Client Y<small>XYZ Holdings</small></button><span className="edge e3"/><span className="edge e4"/><button onClick={()=>setNode('A-104')} className="node account n3">A-104<small>BUY account</small></button><button onClick={()=>setNode('A-882')} className="node account n4">A-882<small>SELL account</small></button></div></section><aside className="entityDetail"><span className="eyebrow">SELECTED ENTITY</span><h2>{node}</h2><p>Relationship path discovered through verified ownership and client-reference records.</p><dl><dt>Resolution</dt><dd>Exact UBO identifier</dd><dt>Confidence</dt><dd>97%</dd><dt>Path</dt><dd>2 ownership hops</dd><dt>Source</dt><dd><a>[Ownership:O29]</a></dd><dt>Other cases</dt><dd>WT-102, FR-118</dd></dl><div className="pathProof"><b>Why trusted</b><span>Client X → Registry ID 774 → UBO-72</span><span>Client Y → Registry ID 881 → UBO-72</span></div><div className="warning">A relationship increases investigative priority. It is not proof that coordination or misconduct occurred.</div></aside></div>}

function ManagementView(){return <div className="modulePage"><div className="managementGrid"><article><span>ALERT-TO-CASE REDUCTION</span><b>67%</b><small>1,247 alerts → 412 cases</small></article><article><span>PRECISION @ TOP DECILE</span><b>81%</b><small>Target ≥ 75% · synthetic validation</small></article><article><span>CASES OUTSIDE SLA</span><b className="bad">18</b><small>4.4% · 6 high priority</small></article><article><span>EVIDENCE COVERAGE</span><b>98.7%</b><small>7 cases below grounding threshold</small></article></div><div className="managementLower triple"><section className="modulePanel"><div className="sectionHead"><div><span className="eyebrow">RISK BY TYPOLOGY</span><h2>Where risk is concentrated</h2></div></div>{[['Wash trading',42,42,'#d64545'],['Spoofing',27,27,'#ee9143'],['Front-running',18,18,'#8b69d8'],['Insider dealing',13,13,'#267f70']].map(x=><div className="dist" key={x[0]}><span>{x[0]}</span><div><i style={{width:`${x[2]}%`,background:x[3]}}/></div><b>{x[1]}%</b></div>)}</section><section className="modulePanel"><div className="sectionHead"><div><span className="eyebrow">CASE AGEING</span><h2>Operational pressure</h2></div></div><div className="ageGrid"><span><b>286</b>&lt; 24 hours</span><span><b>108</b>1–3 days</span><span className="danger"><b>18</b>&gt; 3 days</span></div><div className="actionCallout">Action: rebalance six high-risk cases from Queue B to the senior review team.</div></section><section className="modulePanel healthPanel"><div className="sectionHead"><div><span className="eyebrow">MODEL & DATA HEALTH</span><h2>Controls operating normally</h2></div></div><p><b>● Stable</b> Feature drift <span>PSI 0.08</span></p><p><b>● Stable</b> Score calibration <span>ECE 0.04</span></p><p className="watch"><b>● Watch</b> Ownership freshness <span>7 gaps</span></p><p><b>● Stable</b> Override rate <span>11.2%</span></p></section></div><section className="modulePanel outcomes"><div><span className="eyebrow">MEASURABLE OUTCOMES</span><h2>Evidence that the system adds value</h2></div><div><span><b>42%</b> fewer false positives</span><span><b>31%</b> faster triage</span><span><b>100%</b> decisions attributed</span><span><b>0</b> autonomous closures</span></div><small>Prototype metrics are synthetic. Production claims require validation on approved, representative historical data.</small></section></div>}

function ControlsView(){return <div className="modulePage controlsPage"><section className="controlHero"><div><span className="eyebrow">PRODUCTION READINESS</span><h2>Designed for control, resilience and auditability</h2><p>The prototype makes its boundaries explicit. Each control below maps to an implementation component and an operational owner.</p></div><div className="readiness"><b>12/12</b><span>demo controls evidenced</span></div></section><section className="modulePanel llmArchitecture"><div><span className="eyebrow">CONTROLLED LLM BOUNDARY</span><h2>More useful AI with fewer tokens and less data exposure</h2><p>One structured call returns the summary, counter-hypothesis, evidence gaps, next actions and confidence note. Repeat evidence packets are served from the local cache.</p></div><div className="llmGuardFlow"><span><b>1</b>Local ML</span><i>→</i><span><b>2</b>Eligibility</span><i>→</i><span><b>3</b>DLP + injection guard</span><i>→</i><span><b>4</b>Local micro-RAG</span><i>→</i><span><b>5</b>One LLM call</span><i>→</i><span><b>6</b>Citation verifier</span><i>→</i><span><b>7</b>Human</span></div></section><div className="controlGrid">{[
  ['Human authority','No automated case closure, escalation to regulators, or misconduct determination.','Enforced'],
  ['Evidence grounding','Every material statement must resolve to immutable source IDs; otherwise the copilot abstains.','Enforced'],
  ['Role separation','Investigators recommend; supervisors approve false-positive closure.','Enforced'],
  ['Audit trail','Assignments, evidence views, overrides, decisions and model versions are timestamped.','Enforced'],
  ['Model monitoring','Precision, calibration, drift, overrides and data completeness tracked by typology.','Monitored'],
  ['Data protection','Private network boundary, encryption, least privilege and field-level masking in target design.','Designed'],
  ['Resilience','Idempotent ingestion, retry queues, dead-letter handling and degraded rule-only mode.','Designed'],
  ['Reproducibility','Feature snapshot, source timestamps, code version and model version retained per assessment.','Enforced'],
].map(c=><article key={c[0]}><div><span>✓</span><b>{c[0]}</b><em>{c[2]}</em></div><p>{c[1]}</p></article>)}</div><section className="modulePanel scaleStory"><div><span className="eyebrow">SCALE & FAILURE MODES</span><h2>What happens when dependencies fail</h2></div><div className="failureGrid"><span><b>ML unavailable</b>Continue rule ingestion; queue scoring retries; show degraded mode.</span><span><b>Graph data stale</b>Suppress graph contribution; lower confidence; surface data gap.</span><span><b>Evidence missing</b>Withhold generated narrative; preserve raw records for review.</span><span><b>Duplicate event</b>Idempotency key prevents duplicate cases and audit entries.</span></div></section></div>}

function DataInputView({openScenario,onAccepted,kafka}:{openScenario:()=>void;onAccepted:()=>void;kafka?:KafkaStatus}){
  const [region,setRegion]=useState('EMEA');
  const [businessDate,setBusinessDate]=useState('2026-09-05');
  const [batchId,setBatchId]=useState('SURV-20260905-EMEA');
  const [alertFile,setAlertFile]=useState<File>();
  const [parquetFiles,setParquetFiles]=useState<File[]>([]);
  const [statusMessage,setStatusMessage]=useState('Waiting for the daily file pair');
  const [submitting,setSubmitting]=useState(false);
  const [ready,setReady]=useState(false);
  function updateRegion(value:string){setRegion(value);setBatchId(`SURV-${businessDate.replaceAll('-','')}-${value}`);setReady(false)}
  function updateDate(value:string){setBusinessDate(value);setBatchId(`SURV-${value.replaceAll('-','')}-${region}`);setReady(false)}
  async function submitBatch(){
    if(!alertFile||parquetFiles.length===0)return;
    setSubmitting(true); setStatusMessage('Validating alert contract…');
    try{
      await surveillanceApi.uploadDailyAlerts(alertFile,region,businessDate,batchId);
      setStatusMessage(`Alert file accepted. Validating ${parquetFiles.length} Parquet ${parquetFiles.length===1?'file':'files'} and pairing the batch…`);
      const result=await surveillanceApi.uploadDailyParquet(parquetFiles,region,businessDate,batchId);
      setReady(result.readiness.ready);
      setStatusMessage(result.readiness.ready?`Daily batch is ready with ${result.readiness.parquetFiles} Parquet ${result.readiness.parquetFiles===1?'file':'files'}. Python will scan every part in bounded batches and enrich the existing alerts.`:result.readiness.status);
      setTimeout(onAccepted,6500);
    }catch(error){setReady(false);setStatusMessage(error instanceof Error?error.message:'Daily batch validation failed')}
    finally{setSubmitting(false)}
  }
  return <div className="modulePage inputPage">
    <section className="inputHero"><div><span className="eyebrow">REGION-AWARE DAILY INPUT</span><h2>Pair existing Java alerts with their daily Parquet context.</h2><p>The original rule alert remains immutable. AI reads only the matching regional dataset, adds behavioural and relationship context, and returns an advisory priority for human review.</p></div><div className="inputIsolation"><span>PRIVACY BOUNDARY</span><b>Raw Parquet never reaches the LLM</b><small>Only tokenised metrics and evidence references may leave detection.</small></div></section>
    <section className="modulePanel"><div className="sectionHead"><div><span className="eyebrow">1 · IDENTIFY THE DAILY BATCH</span><h2>Business date and region isolate every run</h2></div><span className="live">DAILY-PAIRED-BATCH v1</span></div><div className="batchControls"><label>Region<select value={region} onChange={event=>updateRegion(event.target.value)}><option>EMEA</option><option>AMER</option><option>APAC</option><option>GLOBAL</option></select></label><label>Business date<input type="date" value={businessDate} onChange={event=>updateDate(event.target.value)}/></label><label>Batch ID<input value={batchId} onChange={event=>{setBatchId(event.target.value);setReady(false)}}/></label></div></section>
    <section className="modulePanel"><div className="sectionHead"><div><span className="eyebrow">2 · PROVIDE THE CORRESPONDING FILES</span><h2>The alert contract and every Parquet part must pass validation</h2></div><span className={ready?'live':'watch'}>{ready?'BATCH READY':'WAITING FOR INPUT'}</span></div><div className="filePairGrid"><label className={alertFile?'fileReady':''}><span>ALERT CONTRACT</span><b>{alertFile?.name||'Choose alerts.json or alerts.jsonl'}</b><small>One existing Java alert file with rule provenance, region, asset class and triggering trade IDs</small><input type="file" accept=".json,.jsonl,application/json" onChange={event=>{setAlertFile(event.target.files?.[0]);setReady(false)}}/></label><label className={parquetFiles.length?'fileReady':''}><span>PARQUET CONTEXT · SINGLE OR MULTI-PART</span><b>{parquetFiles.length?`${parquetFiles.length} file${parquetFiles.length===1?'':'s'} selected`:'Choose one or more .parquet files'}</b><small>{parquetFiles.length?parquetFiles.map(file=>file.name).join(' · '):'All parts must belong to the same business date and region; Python scans each part in bounded row batches'}</small><input type="file" multiple accept=".parquet,application/octet-stream" onChange={event=>{setParquetFiles(Array.from(event.target.files||[]));setReady(false)}}/></label></div><div className="pipeline"><span><b>Java alerts</b>preserved</span><i>+</i><span><b>All Parquet parts</b>validated</span><i>→</i><span><b>ML + anomaly</b>prioritise</span><i>→</i><span><b>Graph</b>clusters cases</span><i>→</i><span><b>Human</b>decides</span></div></section>
    <section className="modulePanel dailyControlResult"><div><span className="eyebrow">3 · CONTROL RESULT</span><h2>{statusMessage}</h2><p>Required in every Parquet file: trade_id, event_time, instrument, asset_class, region, side, quantity, price, account_id and client_id.</p></div><div className="dailyActions"><button className="primary" disabled={!alertFile||parquetFiles.length===0||submitting} onClick={submitBatch}>{submitting?'Validating daily batch…':'Validate and submit daily batch'}</button>{ready&&<button onClick={openScenario}>Open AI scenario →</button>}</div></section>
    <section className="qualityGrid dailyQuality"><article className={alertFile?'good':''}><span>ALERT FILE</span><b>{alertFile?'1 selected':'Required'}</b><small>Original alerts are never overwritten</small></article><article className={parquetFiles.length?'good':''}><span>PARQUET PARTS</span><b>{parquetFiles.length||'Required'}</b><small>One file or multiple part files supported</small></article><article><span>REGION</span><b>{region}</b><small>Cross-region rows are rejected</small></article><article><span>BUSINESS DATE</span><b>{businessDate}</b><small>Day-level reconciliation</small></article><article><span>KAFKA</span><b>{kafka?.enabled?'Active':'Optional'}</b><small>Metadata events only; no raw Parquet</small></article></section>
  </div>
}

const presentationSteps=[
  {number:'01',label:'The challenge',title:'Too many alerts. Not enough investigator time.',copy:'Traditional surveillance creates large queues of isolated alerts. The real challenge is finding the few cases that deserve immediate human attention.',accent:'blue'},
  {number:'02',label:'AI prioritises',title:'AI finds patterns that rules alone can miss.',copy:'The system combines known rules, unusual behaviour, market context and hidden relationships to rank cases consistently.',accent:'green'},
  {number:'03',label:'Evidence explains',title:'Every important statement is connected to evidence.',copy:'Investigators see why a case was prioritised, what increased or reduced risk, and which source records support each claim.',accent:'amber'},
  {number:'04',label:'Human decides',title:'People apply judgement and remain accountable.',copy:'AI cannot determine misconduct or close a case. An authorised investigator reviews the evidence, records a rationale and chooses the outcome.',accent:'teal'},
  {number:'05',label:'Business value',title:'Less noise. Faster review. Stronger governance.',copy:'Management gains clearer workload, measurable model performance, complete decision ownership and visible control health.',accent:'navy'},
];

function PresentationView({openExpert}:{openExpert:(view:View)=>void}){
  const[step,setStep]=useState(0); const current=presentationSteps[step];
  return <div className="presentationPage"><section className="presentationHero"><div><span className="presentationBadge">GUIDED HACKATHON DEMO · 3 MINUTES</span><h2>From <em>1,247 alerts</em> to one<br/>accountable decision.</h2><p>Trade Surveillance Navigator helps investigators focus on the right activity—without handing decision-making authority to AI.</p><div className="heroPrinciple"><span><b>AI</b> finds the signal</span><i>→</i><span><b>Evidence</b> builds trust</span><i>→</i><span><b>People</b> make the decision</span></div></div><div className="heroOutcome"><span>THE OUTCOME</span><b>67%</b><strong>less alert noise</strong><small>1,247 alerts organised into 412 explainable cases</small></div></section>
    <div className="stepNav" role="tablist" aria-label="Presentation steps">{presentationSteps.map((item,index)=><button role="tab" aria-selected={step===index} key={item.number} onClick={()=>setStep(index)} className={step===index?'active':''}><b>{item.number}</b><span>{item.label}</span></button>)}</div>
    <section className={`storyCard ${current.accent}`}><div className="storyCopy"><span className="storyNumber">STEP {current.number} · {current.label.toUpperCase()}</span><h2>{current.title}</h2><p>{current.copy}</p>{step===0&&<div className="challengeMetrics"><span><b>1,247</b> raw alerts</span><i>→</i><span><b>412</b> investigation cases</span><i>→</i><span><b>103</b> high priority</span></div>}{step===1&&<div className="aiSimple"><span><b>Rules</b>Known patterns</span><span><b>Behaviour</b>What is unusual</span><span><b>Context</b>What reduces concern</span><span><b>Links</b>Who is connected</span></div>}{step===2&&<div className="evidenceSimple"><span><b>Why flagged</b>7 repeated opposing cycles</span><span><b>Hidden connection</b>Common beneficial owner</span><span><b>Source proof</b>Trades · positions · ownership</span></div>}{step===3&&<div className="humanSimple"><span>Review evidence</span><i>→</i><span>Apply judgement</span><i>→</i><span>Record rationale</span><i>→</i><b>Own the decision</b></div>}{step===4&&<div className="valueSimple"><span><b>−42%</b> false positives</span><span><b>−31%</b> triage time</span><span><b>100%</b> decisions attributed</span><span><b>0</b> autonomous closures</span></div>}</div>
      <aside className="storyVisual">{step===0&&<><span className="visualIcon">⌁</span><b>Alert overload</b><small>Multiple signals, duplicated work and slow triage</small></>}{step===1&&<><span className="visualIcon ai">AI</span><b>94 / 100</b><small>High priority for human investigation</small><em>AI ASSISTS</em></>}{step===2&&<><span className="visualIcon">✓</span><b>100% cited</b><small>0 unsupported material claims</small><em>EVIDENCE GROUNDED</em></>}{step===3&&<><span className="visualIcon person">◉</span><b>Investigator required</b><small>AI cannot make the final decision</small><em>HUMAN ACCOUNTABLE</em></>}{step===4&&<><span className="visualIcon">↗</span><b>Measurable value</b><small>Better prioritisation with stronger controls</small><em>MANAGEMENT READY</em></>}</aside>
    </section>
    <footer className="presentationActions"><button disabled={step===0} onClick={()=>setStep(x=>Math.max(0,x-1))}>← Previous</button><span>{step+1} of {presentationSteps.length}</span>{step<presentationSteps.length-1?<button className="next" onClick={()=>setStep(x=>Math.min(presentationSteps.length-1,x+1))}>Next: {presentationSteps[step+1].label} →</button>:<button className="next" onClick={()=>openExpert('lab')}>Open live scenario →</button>}</footer>
    <div className="expertPrompt"><span><b>Want the operational detail?</b> The full investigator workbench remains available.</span><button onClick={()=>openExpert('cases')}>Open expert view</button></div>
  </div>
}

export default function Home(){
  const [view,setView]=useState<View>('presentation');
  const [caseSource,setCaseSource]=useState<SurveillanceCase[]>(cases);
  const [live,setLive]=useState(false);
  const [metrics,setMetrics]=useState<ManagementMetrics>();
  const [kafka,setKafka]=useState<KafkaStatus>();
  async function refresh(){try{const [nextCases,nextMetrics,nextKafka]=await Promise.all([surveillanceApi.cases(),surveillanceApi.management(),surveillanceApi.kafka()]);if(nextCases.length)setCaseSource(nextCases);setMetrics(nextMetrics);setKafka(nextKafka);setLive(true)}catch{setLive(false)}}
  useEffect(()=>{const initial=setTimeout(refresh,0);const timer=setInterval(refresh,10000);return()=>{clearTimeout(initial);clearInterval(timer)}},[]);
  const titles:Record<View,string>={presentation:'Guided presentation',input:'Data intake and quality controls',cases:'Evidence-led investigations',lab:'Interactive surveillance scenario lab',clusters:'Related-alert clustering',entities:'Entity and relationship intelligence',management:'Management outcomes and controls',controls:'Production readiness and guardrails'};
  const nav:[View,string,string][]=[['presentation','▶','Presentation mode'],['input','⇩','Data input'],['cases','◇','Cases'],['lab','◉','Scenario lab'],['clusters','⌁','Alert clusters'],['entities','◎','Entity intelligence'],['management','▥','Management view'],['controls','✓','Controls & readiness']];
  return <main className="shell"><aside className="rail"><div className="brand"><span className="brandMark">T</span><span>TRADE<span className="muted">/SURVEILLANCE NAVIGATOR</span></span></div><nav>{nav.map(([key,icon,label],index)=><button key={key} onClick={()=>setView(key)} className={`${view===key?'navActive':''} ${index===1?'expertStart':''}`}>{icon} {label}{key==='presentation'&&<em>START</em>}{key==='input'&&<em>NEW</em>}{key==='cases'&&<b>{caseSource.length}</b>}{key==='lab'&&<em>LIVE</em>}</button>)}</nav><div className="principle"><span>CONTROL PRINCIPLE</span><strong>AI prioritises.</strong><strong>Evidence explains.</strong><strong>Human decides.</strong></div><div className="version">{live?`LIVE API + ${kafka?.enabled?'KAFKA':'POSTGRESQL'}`:'CONTROLLED DEMO FALLBACK'}<br/>MODEL HYBRID v1.0</div></aside><section className="workspace"><header className={`top ${view==='presentation'?'presentationTop':''}`}><div><span className="eyebrow">{view==='presentation'?'PRESENTATION MODE':view==='input'?'GOVERNED INGESTION':view==='management'?'MANAGEMENT DASHBOARD':view==='lab'?'DEMONSTRATION LAB':'SURVEILLANCE WORKBENCH'}</span><h1>{titles[view]}</h1></div>{view!=='presentation'&&view!=='input'&&<div className="topStats"><span><b>{live?'LIVE':'DEMO'}</b> mode</span><i>→</i><span><b>{metrics?.cases??caseSource.length}</b> cases</span><i>→</i><span className="red"><b>{metrics?.highPriority??caseSource.filter(item=>item.risk>=80).length}</b> high priority</span></div>}</header>{view==='presentation'?<PresentationView openExpert={setView}/>:view==='input'?<DataInputView openScenario={()=>setView('lab')} onAccepted={refresh} kafka={kafka}/>:view==='cases'?<CasesView caseSource={caseSource} live={live}/>:view==='lab'?<ScenarioLab/>:view==='clusters'?<ClustersView/>:view==='entities'?<EntitiesView/>:view==='management'?<ManagementView/>:<ControlsView/>}</section></main>
}
